In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("ecommerce_sales_dirty_2024_2025.csv")

In [3]:
df

,Order_ID,Order_Date,Customer_ID,Category,Product,Region,City,Customer_Segment,Units,Unit_Price,Discount_Percent,Revenue,Cost,Profit,Payment_Method,Order_Status
0,ORD00001,2024-01-18,CUST1127,Clothing,T-Shirt,East,Patna,Corporate,4,1893.0,5.0,7193.40,5754.536983,1438.863017,UPI,Delivered
1,ORD00002,2025-02-24,CUST1040,Furniture,Table Lamp,East,Bhubaneswar,Small Business,1,8685.0,15.0,7382.25,5074.974937,2307.275063,Cash on Delivery,Delivered
2,ORD00003,2024-06-29,CUST1077,Electronics,Smartwatch,South,Bengaluru,Consumer,2,12694.0,15.0,21579.80,13672.201988,7907.598012,Net Banking,Delivered
3,ORD00004,2025-01-29,CUST1159,Electronics,Smartwatch,East,Patna,Consumer,3,23812.0,15.0,60720.60,40702.615339,20017.984661,Net Banking,Delivered
4,ORD00005,2024-12-25,CUST1358,Electronics,Headphones,East,Kolkata,Corporate,4,50902.0,5.0,193427.60,120626.016563,72801.583437,Debit Card,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2015,ORD00070,2025-05-22,CUST1202,Electronics,Smartphone,East,Kolkata,Corporate,5,59293.0,15.0,251995.25,197509.832042,54485.417958,UPI,Delivered
2016,ORD00855,2024-12-05,CUST1429,Beauty,Moisturizer,West,Pune,Corporate,2,2746.0,20.0,4393.60,2776.907043,1616.692957,Debit Card,Delivered
2017,ORD01603,2025-09-30,CUST1133,Beauty,Moisturizer,East,NaN,Small Business,5,2049.0,0.0,10245.00,6501.358826,3743.641174,Net Banking,Delivered
2018,ORD01221,2024-03-15,CUST1005,Electronics,Smartwatch,West,Ahmedabad,Corporate,4,62138.0,20.0,198841.60,138275.106923,60566.493077,UPI,Cancelled
2019,ORD01404,2024-12-22,CUST1362,Beauty,Shampoo,South,Bengaluru,Small Business,5,2187.0,15.0,9294.75,7056.904764,2237.845236,Cash on Delivery,Delivered

In [4]:
df.shape

(2020, 16)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          2020 non-null   object
 1   Order_Date        2020 non-null   object
 2   Customer_ID       2020 non-null   object
 3   Category          2020 non-null   object
 4   Product           2020 non-null   object
 5   Region            2020 non-null   object
 6   City              1959 non-null   object
 7   Customer_Segment  1968 non-null   object
 8   Units             2020 non-null   int64
 9   Unit_Price        1989 non-null   float64
 10  Discount_Percent  1939 non-null   float64
 11  Revenue           1909 non-null   float64
 12  Cost              1909 non-null   float64
 13  Profit            1909 non-null   float64
 14  Payment_Method    1960 non-null   object
 15  Order_Status      2020 non-null   object
dtypes: float64(5), int64(1), object(10)
memory usage: 252.6+ KB

In [6]:
df.describe()

,Units,Unit_Price,Discount_Percent,Revenue,Cost,Profit
count,2020.000000,1989.000000,1939.000000,1.909000e+03,1.909000e+03,1909.000000
mean,3.128218,11082.775767,12.635379,3.167170e+04,2.250109e+04,9170.612640
std,3.446455,16426.614801,9.040193,8.328675e+04,6.374733e+04,20817.209046
min,1.000000,150.000000,0.000000,1.300500e+02,7.551448e+01,53.994371
25%,2.000000,2022.000000,5.000000,3.992400e+03,2.738354e+03,1076.323558
50%,3.000000,3956.000000,10.000000,9.756000e+03,6.830201e+03,2722.731314
75%,4.000000,11289.000000,20.000000,2.641600e+04,1.871842e+04,7758.553309
max,100.000000,69371.000000,90.000000,2.841840e+06,2.265000e+06,576840.194052

In [7]:
df.isnull().sum()

Order_ID              0
Order_Date            0
Customer_ID           0
Category              0
Product               0
Region                0
City                 61
Customer_Segment     52
Units                 0
Unit_Price           31
Discount_Percent     81
Revenue             111
Cost                111
Profit              111
Payment_Method       60
Order_Status          0
dtype: int64

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df['Category']=df['Category'].replace ('electronics','Electronics')

In [10]:
df['Category']=df['Category'].replace ('Clothng','Clothing')

In [11]:
df['Category']=df['Category'].replace (' ELECTRONICS ','Electronics')

In [12]:
df['Payment_Method']=df['Payment_Method'].replace('UPI','upi')

In [13]:
df['Payment_Method']=df['Payment_Method'].replace('Credit Card','Credit card')

In [14]:
df['Category'].unique()

array(['Clothing', 'Furniture', 'Electronics', 'Beauty', 'Home'],
      dtype=object)

In [15]:
df['Payment_Method'].unique()

array(['upi', 'Cash on Delivery', 'Net Banking', 'Debit Card',
       'Credit card', nan], dtype=object)

In [16]:
df['Customer_Segment']=df['Customer_Segment'].fillna(df['Customer_Segment'].mode()[0])

In [17]:
df['Unit_Price']=df['Unit_Price'].fillna(df['Unit_Price'].median())

In [18]:
df['Discount_Percent']=df['Discount_Percent'].fillna(df['Discount_Percent'].median())

In [19]:
df['Revenue']=df['Revenue'].fillna(df['Revenue'].median())

In [20]:
df['Cost']=df['Cost'].fillna(df['Cost'].median())

In [21]:
df['Profit']=df['Profit'].fillna(df['Profit'].median())

In [22]:
df['Payment_Method']=df['Payment_Method'].fillna(df['Payment_Method'].mode()[0])

In [ ]:
df['City'] = df.groupby('Region')['City'].transform(
    lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown')
)